[tool.poetry]
name = "legisplain"
version = "0.1.0"
description = ""
authors = ["Gabriel Altay <gabriel.altay@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
united-states-congress = {git = "https://github.com/unitedstates/congress.git"}
typer = "^0.12.3"
rich = "^13.7.1"
beautifulsoup4 = "^4.12.3"
psycopg2-binary = "^2.9.9"
pydantic = "^2.7.3"
pandas = "^2.2.2"
sqlalchemy = "^2.0.30"
huggingface-hub = "^0.23.3"
pyarrow = "^16.1.0"
datasets = "^2.19.2"
unstructured = "^0.14.6"
duckdb = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
